


buttons:
  - name: play
    note: 41
    lights-on:
      - 41
    lights-off:
      - 42
    command: [playerctl, -p, spotify, play]

  - name: pause
    note: 42
    lights-off:
      - 41
    command: [playerctl, -p, spotify, pause]


sliders:
  - name: spotify volume
    note: 0
    command: input-volume
    matches: # matches pulse input sink name
      - Spotify
