init:
  - name: Lights off
    lights-off:
      - 41
      - 42

  - name: set play active
    lights-on:
      - 41
    when: [playerctl, -p, spotify, status]
    equals: Playing
    interval: 10


buttons:
  - name: play
    note: 41
    lights-on:
      - 41
    lights-off:
      - 42
    command: [playerctl, -p, spotify, play]

  - name: pause
    note: 42
    lights-off:
      - 41
    command: [playerctl, -p, spotify, pause]


sliders:
  - name: spotify volume
    note: 0
    command: input-volume
    matches: # matches proplist.application.name
      - spotify

  - name: Browser volume
    note: 1
    command: input-volume
    matches: # matches proplist.application.name
      - vivaldi-bin

  - name: Chat volume
    note: 2
    command: input-volume
    matches: # matches proplist.application.name
      - signal-desktop